# Identifier for featurization results. Can be used to query 
# featurization results in DB. 
# Multiple runs with the same identifier will REPLACE previous
# results with matching run_id. 
# Passing 'randomize' will generate a random run_id (UUID). 
run_id: 'default-10k'

# Date to use as the "current date" for expungement classification. 
# Records after this cutoff will be filtered out, and this date will
# be used to decide whether records are still pending expungement 
# eligibility (see 'years_pending_after_misdemeanor/felony')
cutoff_date: '2020-12-31'

# Sections of Virginia Legal Code that qualify for various levels
# of expungement eligibility
covered_sections_a:
  - 4.1-305
  - 18.2-250.1
covered_sections_b:
  - 4.1-305
  - 18.2-96
  - 18.2-103
  - 18.2-119
  - 18.2-120
  - 18.2-134
  - 18.2-250.1
  - 18.2-415
covered_sections_b_misdemeanor:
  - 18.2-248.1
excluded_sections_twelve:
  - 18.2-36.1
  - 18.2-36.2
  - 18.2-51.4
  - 18.2-51.5
  - 18.2-57.2
  - 18.2-266
  - 46.2-341.24

# Time passed since last arrest or felony conviction
years_since_arrest: 3
years_since_felony: 10

# Time gap that must exist between record and person's next conviction 
# to make a record eligible for expungement
years_until_conviction_after_misdemeanor: 7
years_until_conviction_after_felony: 10

# Time that a record is pending for expungement until fully eligible, 
# depending on type of offense. 
# Example: a felony record is pending if it is within X years of the 
# above 'cutoff_date'
years_pending_after_misdemeanor: 7
years_pending_after_felony: 10

# If true, a single person cannot have more than 2 lifetime expungements
lifetime_rule: true

# If true, if a person has an offense that would be automatically expungeable
# that is on same day as an offense of theirs that is NOT automatically
# expungeable, the offense that would be automatic must instead be petitioned
sameday_rule: true
