---
title: "Current State of Expungeable Records"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r, message=F}
# first you need to install these packages
library(httr)
library(tidyverse)
library(data.table)
library(fs)
library(here)
source(here("code", "helper-functions.R"))
```

# Full data
Here are the high-level counts for _all years_ in the data.

```{r}
all_df <- read_csv("~/expunge_counts.csv", col_types = "cnnnnn")
sums <- summarise(all_df, across(2:6, sum, na.rm = TRUE))
sums
```

```{r, include = F}
# it looks like we lost 300k cases somewhere in the new law counts
# might need to look into that
new_law_total <- sums$automatic + sums$petition + sums$not_eligible
old_law_total <- sums$old_petition + sums$old_not_eligible
print(old_law_total - new_law_total)

View(filter(all_df, is.na(automatic)))
```


## Results for the New Law

```{r}
.c <- names(sums)
.l <- c(
  "Automatic Exp.",
  "Exp. w/ Petition",
  "Not Eligible",
  "Exp. w/ Petition",
  "Not Eligible"
)

sums %>%
  pivot_longer(automatic:old_not_eligible) %>%
  mutate(
    law = ifelse(str_detect(name, "old"), "Old Law", "New Law"),
    name = factor(name, levels = .c, labels = .l),
  ) %>%
  ggplot(aes(x = name, y = value/1e6)) +
    geom_bar(stat = "identity") + 
    facet_wrap(~law) +
    ylab("Count of Cases (in Millions)") + xlab("") +
    ggtitle("Counts of Cases for entire data set (2005-2019)")

```
